# Generated by Django 6.0.5 on 2026-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('designation', models.CharField(default='Unknown', max_length=100)),
                ('emp_type', models.CharField(default='Unknown', max_length=100)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
